# Generated by Django 5.2.7 on 2025-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactsubmission_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
