# Generated by Django 5.2.7 on 2025-11-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/heroes/'),
        ),
    ]
